[libgcrypt]
#source = "git"
#git = "https://git.gnupg.org/libgcrypt.git"
#git = "git://git.gnupg.org/libgcrypt.git"
#use_max_tag = true

source = "regex"
regex = "libgcrypt-([\\d.]+)\\."
url = "https://www.gnupg.org/download/integrity_check.html"
