[libgpg-error]
#source = "git"
#git = "https://git.gnupg.org/libgpg-error.git"
#git = "git://git.gnupg.org/libgcrypt-error.git"
#use_max_tag = true

source = "regex"
regex = "libgpg-error-([\\d.]+)\\."
url = "https://www.gnupg.org/download/integrity_check.html"
